name: Update Flipped Images

env:
  GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
  API_URL: ${{ secrets.API_URL }}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install

      - run: node index.js
        env:
          GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
          API_URL: ${{ secrets.API_URL }}

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add ./images/
            git commit -m "ci(images): commit updated character images"
            git push
          else
            echo "No changes detected"
          fi
